### PR TITLE
fix scheduled test

### PR DESCRIPTION
**Pull request by pk910**
some fixes to make the workflow work:
~https://github.com/ethpandaops/verkle-devnets/actions/runs/8597986104~

fixed timeout:
~https://github.com/ethpandaops/verkle-devnets/actions/runs/8603127670~

retry due to weird reorg:
https://github.com/ethpandaops/verkle-devnets/actions/runs/8614286311

### CODE REVIEW

**Comment by parithosh** [comment]
should we wait for the run or merge it in?

**Review by barnabasbusa — APPROVED** [review]

**Comment by parithosh** [comment]
How long is the transition expected to take? seems like post 16h we're just waiting around for a timeout?

**Comment by pk910** [comment]
Yea, there's definitely something wrong.

Unfortunately github is not very good at showing logs from the past 17h on one page. 
The workflow run logs are pretty much useless for me :(

I've grabbed the logs from the running enclave locally (`kurtosis enclave dump`) and uploaded it here:
https://dev.pk910.de/dl/verkle-conv-8603127670.tar.gz

There are 2 lodestar-geth nodes, the first node completed the conversion around 4am and works fine.
The second node stopped proposing & attesting after epoch 1. 
The CL reports EL is syncing. EL reports nothing unusual, but keeps reporting the conversion is still running via it's api.

Because the 2nd node still reports the conversion is running and it looks like it'll do so forever, the test will actually never complete..
I've added a timeout to the conversion test, so the next run will stop if the conversion didn't complete within 12h.

**Comment by pk910** [comment]
retry:  https://github.com/ethpandaops/verkle-devnets/actions/runs/8614286311

**Pull request merged**
